### ISSUE TITLE
unrecognized midi messages

### ISSUE THREAD

**Issue by webern** [webern/midi_file#1]
**Describe the bug**

Comment-out the `#[ignore]` statements for the following tests (in `tests/roundtrip.rs`) and you will find that each hits a byte that I don't understand:
- als_die_roemer (`0x03`)
- phobos_dorico (`0x00`)
- tobeefree (`0x00`)

All of these occur after processing variable length quantity 'delta time', and on the next byte where we expect to see either `0xF0 | 0xF7` (sysex), `0xFF` (meta), of some midi message. However there are no MIDI messages that I am aware of that start with `0x0`. I'm stumped, I don't see anything in the spec to help me out here.

**Comment by zigazeljko** [comment]
This is called [running status](http://midi.teragonaudio.com/tech/midispec/run.htm).

To summarize: if the first byte of a midi message (the status byte) is equal to the previous one, it can be omitted. Parsing this is unambiguous, since status is always in range from `0x80` to `0xFF`, while remaining bytes are in range from `0x00` to `0x7F`.

**Comment by webern** [comment]
💡 💡 💡 Thank you!
